name: RUZ Daily Schedule

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

jobs:
  get-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requests
        run: pip install requests

      - name: Get RUZ schedule
        run: python ruz_client.py
